/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About | KiroKeys</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="pt-36 ">
        <div className="w-2/5">
          <h1 className="text-7xl pb-16 text-[#183E43]">
            KIRO-KEYS <br/><span className="text-[#3EB0AC]">The Smarter Dashlane</span>
          </h1>
          <div className="text-xl   py-10  tracking-wide">
          Whats yours is only yours and no one has a right on it!
          One stop solution to password privacy and management with your data right in your hands anytime, anywhere.
          </div>
          <div className="flex pt-10 justify-between">
            <div className=" w-[40%] text-2xl text-center rounded-full border-2 border-[#FCE2DB] bg-[#FCE2DB] py-6 px-12 cursor-pointer hover:bg-transparent ">Register</div>
            <div className=" w-[40%] text-2xl py-6 px-12 text-center rounded-full border-2 border-[#F9E596] cursor-pointer hover:bg-[#FCE2DB] ">Learn More</div>
          </div>
        </div>
        
        <img src='./assets/homepage-bg/Ellipse16.png' alt="Ellipse16" className='absolute top-12 right-24 ' width={750} />
        <img src='./assets/homepage-bg/Ellipse13.png' alt="Ellipse13" className='absolute top-0 right-0' width={700} />
        <img src='./assets/homepage-bg/Ellipse15.png' alt="Ellipse15" className='absolute top-0 right-0' width={600} />

      </div>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
